CREATE TABLE tb_usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    input_nome_cadastro VARCHAR(255),
    input_cpf_cadastro INTEGER,
    input_email_cadastro VARCHAR(255),
    input_senha_cadastro VARCHAR(255),
    input_data_nascimento_cadastro DATE,
    input_telefone INTEGER
);
INSERT INTO tb_usuario (input_nome_cadastro, input_cpf_cadastro, input_email_cadastro, input_senha_cadastro, input_telefone)
VALUES ('Usuário fictício legado', 1234567890, 'legado@example.com', 'SenhaLegada', 900000000);

CREATE TABLE tb_veiculo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    placa VARCHAR(255), modelo VARCHAR(255), cor VARCHAR(255), observacao VARCHAR(255), hora_entrada TIMESTAMP(6)
);
INSERT INTO tb_veiculo (placa, modelo, cor, hora_entrada)
VALUES ('LEG8H90', 'Veículo fictício legado', 'Branco', TIMESTAMP '2026-10-01 09:00:00');
